### PR TITLE
ToArray function

### PR DESCRIPTION
**Pull request by kalaninja**
A new function to save data into an array

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
Do you think people are really going to need this one? Sounds a bit tedious to me especially because you can get "index out of bounds" easily.

**Comment by kalaninja** [comment]
no "index out of bounds" actually, there is a length check, so it populates only the available array size. look for the tests, there are such cases

**Comment by ahmetalpbalkan** [comment]
Hmm so the elements beyond the length goes discarded... My concern is that people new to Go may try to use Arrays when they should be using Slices in fact (I most certainly did that), and this method would give them the idea that this is exactly like .NET ToArray() maybe and they sign up for bugs without realizing.

Is there a way perhaps we can make ToSlice work with arrays (and panic when cap is not enough) so that nothing gets discarded "silently"?

I might be overthinking but I don't think arrays have so much use in practical Go land and in go-linq type of scenarios.

**Comment by kalaninja** [comment]
@ahmetalpbalkan I agree that arrays in Go aren't very popular. That is probably why I've done this method only now. Making ToSlice work with array is probably not a good idea, mainly because of its name "ToSlice") 

I see the main purpose of this method is to fill the gap, because we have "To-" methods to all other Go types.

**Comment by ahmetalpbalkan** [comment]
You're right we should probably not make ToSlice accept arrays. I say let's try not adding this until somebody asks for it. If it is cruicial, it will probably come up in a feature request. Adding this may make the API seem complete at the expense of confusing Go beginners and increasing the API surface with methods that are not really used.

**Comment by kalaninja** [comment]
OK

**Comment by ahmetalpbalkan** [comment]
Thanks!

**Pull request closed without merging**
